<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <Description>Azure Table Storage (and Cosmos DB Table API) provider for Shiny.DocumentDb</Description>
        <PackageTags>azuretable;tablestorage;azure;cosmos;documentdb;json;nosql;shiny</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Data.Tables" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Shiny.DocumentDb.Tests" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.DocumentDb\Shiny.DocumentDb.csproj" />
    </ItemGroup>
</Project>
