using System.Text.Json;
using Shiny.DocumentDb.Sqlite;
using Shiny.DocumentDb.Tests.Fixtures;
using Xunit;

namespace Shiny.DocumentDb.Tests;

// MapIdType (custom Id converters) coverage — strongly-typed Id wrapper over SQLite.
public class StronglyTypedIdTests : IDisposable
{
    static readonly TestJsonContext ctx = new(new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase });

    sealed class OrderIdConverter : DocumentIdConverter<OrderId>
    {
        public override string ToStorageString(OrderId id) => id.Value.ToString("N");
        public override OrderId FromStorageString(string id) => new(Guid.ParseExact(id, "N"));
        public override bool IsDefault(OrderId id) => id.Value == Guid.Empty;
        public override bool TryGenerate(out OrderId id) { id = OrderId.New(); return true; }
    }

    static DocumentStore CreateStore(Action<DocumentStoreOptions>? configure = null)
    {
        var opts = new DocumentStoreOptions
        {
            DatabaseProvider = new SqliteDatabaseProvider("Data Source=:memory:"),
            JsonSerializerOptions = ctx.Options,
            TableName = $"t{Guid.NewGuid():N}"
        };
        if (configure != null)
            configure(opts);
        else
            opts.MapIdType(new OrderIdConverter());
        return new DocumentStore(opts);
    }

    readonly DocumentStore store = CreateStore();

    public void Dispose() => this.store.Dispose();

    [Fact]
    public async Task TypedId_AutoGenerated_WhenDefault()
    {
        var model = new TypedIdModel { Name = "Alice", Age = 30 };
        Assert.Equal(default, model.Id);

        await this.store.Insert(model, ctx.TypedIdModel);

        Assert.NotEqual(default, model.Id);

        var fetched = await this.store.Get<TypedIdModel>(model.Id, ctx.TypedIdModel);
        Assert.NotNull(fetched);
        Assert.Equal(model.Id, fetched!.Id);
        Assert.Equal("Alice", fetched.Name);
    }

    [Fact]
    public async Task TypedId_Preserved_WhenExplicit()
    {
        var id = OrderId.New();
        var model = new TypedIdModel { Id = id, Name = "Bob", Age = 40 };

        await this.store.Insert(model, ctx.TypedIdModel);

        Assert.Equal(id, model.Id);

        var fetched = await this.store.Get<TypedIdModel>(id, ctx.TypedIdModel);
        Assert.NotNull(fetched);
        Assert.Equal(id, fetched!.Id);
        Assert.Equal("Bob", fetched.Name);
    }

    [Fact]
    public async Task TypedId_Update_And_Remove()
    {
        var model = new TypedIdModel { Name = "Carol", Age = 5 };
        await this.store.Insert(model, ctx.TypedIdModel);

        model.Age = 6;
        await this.store.Update(model, ctx.TypedIdModel);
        var updated = await this.store.Get<TypedIdModel>(model.Id, ctx.TypedIdModel);
        Assert.Equal(6, updated!.Age);

        await this.store.Remove<TypedIdModel>(model.Id);
        Assert.Null(await this.store.Get<TypedIdModel>(model.Id, ctx.TypedIdModel));
    }

    [Fact]
    public async Task TypedId_Query_ByOtherProperty()
    {
        await this.store.Insert(new TypedIdModel { Name = "Dave", Age = 41 }, ctx.TypedIdModel);
        await this.store.Insert(new TypedIdModel { Name = "Eve", Age = 22 }, ctx.TypedIdModel);

        var results = await this.store.Query(ctx.TypedIdModel).Where(x => x.Age > 30).ToList();

        Assert.Single(results);
        Assert.Equal("Dave", results[0].Name);
    }

    [Fact]
    public async Task DelegateOverload_RegistersConverter()
    {
        using var s = CreateStore(o => o.MapIdType<OrderId>(
            toString: id => id.Value.ToString("N"),
            parse: str => new OrderId(Guid.ParseExact(str, "N")),
            isDefault: id => id.Value == Guid.Empty,
            generate: OrderId.New));

        var model = new TypedIdModel { Name = "Frank" };
        await s.Insert(model, ctx.TypedIdModel);

        Assert.NotEqual(default, model.Id);
        var fetched = await s.Get<TypedIdModel>(model.Id, ctx.TypedIdModel);
        Assert.Equal("Frank", fetched!.Name);
    }

    [Fact]
    public async Task NoGenerator_Throws_OnDefaultInsert()
    {
        // converter without a generate delegate → default Id cannot be auto-filled
        using var s = CreateStore(o => o.MapIdType<OrderId>(
            toString: id => id.Value.ToString("N"),
            parse: str => new OrderId(Guid.ParseExact(str, "N")),
            isDefault: id => id.Value == Guid.Empty));

        var model = new TypedIdModel { Name = "Grace" };

        await Assert.ThrowsAsync<InvalidOperationException>(
            () => s.Insert(model, ctx.TypedIdModel));
    }
}
