using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using Microsoft.Data.Sqlite;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging.Abstractions;
using ShinyDocDbMyAdmin.Services;

// Emits deploy/demo/seed-demo-volume.sql - the bulk documents the public playground opens on, on
// top of the varied sample seed-demo.py writes.
//
// Why this exists rather than more Python: the rows are produced by the *same* DocumentGenerator the
// Generate tab runs, against a real database built from seed-demo.sql. So the shipped sample is
// literally what the tool would make from that seed, and there is no second implementation of
// "documents that look like these" to drift out of step.
//
// Deterministic: fixed seeds per type, and the generator draws even its GUIDs from the seeded RNG,
// so re-running produces a byte-identical file and an empty diff unless the seed or counts changed.
//
//     dotnet run --project tools/ShinyDocDbMyAdmin.DemoVolume

// (typeName, how many to add, RNG seed) - seeds are arbitrary but fixed, so output is stable.
var Plan = new (string Type, int Count, int Seed)[]
{
    ("Order", 4_000, 20260731),
    ("Customer", 1_200, 20260732),
    ("Product", 600, 20260733)
};

const string Table = "documents";

var repoRoot = FindRepoRoot();
var seedSql = Path.Combine(repoRoot, "deploy", "demo", "seed-demo.sql");
var outputSql = Path.Combine(repoRoot, "deploy", "demo", "seed-demo-volume.sql");

if (!File.Exists(seedSql))
{
    Console.Error.WriteLine($"Could not find {seedSql}. Run seed-demo.py first.");
    return 1;
}

SQLitePCL.Batteries_V2.Init();

// A scratch database, built from the same SQL the deployment loads - so the generator profiles
// exactly the documents the playground will actually contain.
var work = Path.Combine(Path.GetTempPath(), $"demovolume_{Guid.NewGuid():N}");
Directory.CreateDirectory(work);
var databasePath = Path.Combine(work, "seed.db");

try
{
    Console.WriteLine($"loading {Path.GetFileName(seedSql)} into a scratch database…");
    await using (var connection = new SqliteConnection($"Data Source={databasePath}"))
    {
        await connection.OpenAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = await File.ReadAllTextAsync(seedSql);
        await command.ExecuteNonQueryAsync();
    }

    var admin = BuildAdmin(databasePath, work, out var profileId, out var connections);

    using (connections)
    {
        var before = await Counts(admin, profileId);
        var sql = new StringBuilder();

        sql.AppendLine("-- Generated by tools/ShinyDocDbMyAdmin.DemoVolume - do not edit by hand.");
        sql.AppendLine("--");
        sql.AppendLine("-- Bulk documents for the playground, produced by the admin tool's own DocumentGenerator");
        sql.AppendLine("-- from the sample in seed-demo.sql: numbers inside the observed range, dates inside the");
        sql.AppendLine("-- observed span, categorical fields drawn from the set actually used.");
        sql.AppendLine("--");
        sql.AppendLine("-- These rows carry NO sidecars. The generator writes through the schema-free collection");
        sql.AppendLine("-- lane, which maintains none - so they have no temporal history and no blobs, and only");
        sql.AppendLine("-- the sample from seed-demo.sql populates the History and Blobs tabs. That is deliberate:");
        sql.AppendLine("-- it is also what the Generate tab does, and the tool reports it.");
        sql.AppendLine("--");
        sql.AppendLine("-- Regenerate:  dotnet run --project tools/ShinyDocDbMyAdmin.DemoVolume");
        sql.AppendLine();

        foreach (var (type, count, seed) in Plan)
        {
            var shape = await admin.AnalyzeShape(profileId, Table, type);
            var preview = DocumentAdminService.Preview(shape, count, seed);
            var result = await admin.Commit(profileId, Table, type, preview);

            Console.WriteLine(
                $"  {type,-9} learned from {shape.Samples,3} sample(s) -> generated {result.Written:N0}" +
                (result.StaleSidecars.Count == 0
                    ? ""
                    : $"   (no sidecar for: {string.Join(", ", result.StaleSidecars)})"));

            sql.AppendLine($"-- {type}: {result.Written:N0} generated from {shape.Samples} sample(s), seed {seed}");
        }

        sql.AppendLine();
        await AppendRows(databasePath, before, sql);

        await File.WriteAllTextAsync(outputSql, sql.ToString());

        var bytes = new FileInfo(outputSql).Length;
        Console.WriteLine($"\nwrote {outputSql} ({bytes / 1024.0 / 1024.0:0.00} MB)");
    }

    return 0;
}
finally
{
    try { Directory.Delete(work, recursive: true); }
    catch (IOException) { /* a driver still holding the file is not a failure */ }
}

// ── Helpers ─────────────────────────────────────────────────────────────

static DocumentAdminService BuildAdmin(
    string databasePath, string workDirectory, out string profileId, out ConnectionManager connections)
{
    var configuration = new ConfigurationBuilder()
        .AddInMemoryCollection(new Dictionary<string, string?>
        {
            ["ShinyDocDbMyAdmin:DataDirectory"] = Path.Combine(workDirectory, "admin"),
            ["ShinyDocDbMyAdmin:SecretKey"] = "demo-volume-tool",
            ["ConnectionStrings:seed"] = $"Data Source={databasePath}",
            ["Shiny:DocumentDb:seed:Provider"] = "Sqlite"
        })
        .Build();

    var paths = new AppPaths(configuration);
    var protector = new SecretProtector(configuration, paths, NullLogger<SecretProtector>.Instance);
    var provided = new ProvidedConnections(configuration, NullLogger<ProvidedConnections>.Instance);

    // Demo mode off: this tool *builds* the sample a demo instance later serves, so it needs the
    // write paths a demo instance closes.
    var demo = new DemoMode(configuration, NullLogger<DemoMode>.Instance);
    var profiles = new ProfileStore(paths, protector, provided, demo);

    profileId = provided.Profiles.Single().Id;
    connections = new ConnectionManager(profiles, NullLogger<ConnectionManager>.Instance);

    return new DocumentAdminService(connections, NullLogger<DocumentAdminService>.Instance);
}

/// <summary>
/// What was already in the database before generating: the ids, so only new rows are emitted, and
/// the span their envelope timestamps cover, so generated rows can be dated to match.
/// </summary>
static async Task<Baseline> Counts(DocumentAdminService admin, string profileId)
{
    var existing = new HashSet<string>(StringComparer.Ordinal);
    DateTimeOffset? earliest = null;
    DateTimeOffset? latest = null;

    foreach (var type in await admin.ListTypes(profileId, Table))
    {
        await foreach (var row in admin.StreamAll(profileId, Table, type.TypeName, new BrowseQuery()))
        {
            existing.Add($"{row.TypeName}|{row.Id}");

            foreach (var value in new[] { row.CreatedAt, row.UpdatedAt }.OfType<DateTimeOffset>())
            {
                earliest = earliest is { } e ? (value < e ? value : e) : value;
                latest = latest is { } l ? (value > l ? value : l) : value;
            }
        }
    }

    return new Baseline(
        existing,
        earliest ?? DateTimeOffset.UtcNow.AddYears(-1),
        latest ?? DateTimeOffset.UtcNow);
}

/// <summary>
/// Emits INSERTs for the generated rows only, ordered by (TypeName, Id) so the file is stable
/// between runs regardless of what order the engine hands rows back.
/// </summary>
/// <remarks>
/// The envelope timestamps are replaced rather than passed through. The write path stamps
/// <c>UtcNow</c>, which makes the file differ on every run <i>and</i> gives all several thousand rows
/// the same Updated value - so Browse's default sort would show one flat block and the column would
/// tell you nothing. They are recomputed from a stable hash of the id, spread across the span the
/// hand-written sample already covers.
/// </remarks>
static async Task AppendRows(string databasePath, Baseline baseline, StringBuilder sql)
{
    var existing = baseline.Ids;
    var span = baseline.Latest - baseline.Earliest;
    if (span <= TimeSpan.Zero)
        span = TimeSpan.FromDays(365);

    await using var connection = new SqliteConnection($"Data Source={databasePath}");
    await connection.OpenAsync();

    await using var command = connection.CreateCommand();
    command.CommandText =
        $"SELECT Id, TypeName, Data, CreatedAt, UpdatedAt FROM \"{Table}\" ORDER BY TypeName, Id";

    await using var reader = await command.ExecuteReaderAsync();
    var written = 0;

    while (await reader.ReadAsync())
    {
        var id = reader.GetString(0);
        var typeName = reader.GetString(1);

        // Only the rows this run generated; everything else came from seed-demo.sql and is already
        // in the file the deployment loads first.
        if (!existing.Contains($"{typeName}|{id}"))
        {
            var data = Localise(reader.GetString(2), StableHash($"geo|{typeName}|{id}"));

            // Spread deterministically across the sample's own span. Two draws from the same stable
            // hash, so a document's Updated is always at or after its Created.
            //
            // Divided by 2^n rather than 2^n-1 so neither draw can land exactly on 1.0. With /255
            // about one row in 255 pinned Updated to the maximum, which put a block of a dozen
            // identical timestamps at the top of Browse's default sort - the first thing anyone sees.
            var hash = StableHash($"{typeName}|{id}");
            var created = baseline.Earliest + span * ((hash & 0xFFFF) / 65_536.0);
            var updated = created + (baseline.Latest - created) * (((hash >> 16) & 0xFF) / 256.0);

            sql.Append($"INSERT INTO \"{Table}\" (Id, TypeName, Data, CreatedAt, UpdatedAt) VALUES (");
            sql.Append(Quote(id)).Append(", ");
            sql.Append(Quote(typeName)).Append(", ");
            sql.Append(Quote(data)).Append(", ");
            sql.Append(Quote(Stamp(created))).Append(", ");
            sql.Append(Quote(Stamp(updated))).AppendLine(");");
            written++;
        }
    }

    Console.WriteLine($"  emitted {written:N0} INSERT statement(s)");
}

/// <summary>
/// Pulls multi-vertex geometry back into a plausible local shape around the document's own point.
/// </summary>
/// <remarks>
/// <para>
/// The generator draws every coordinate independently from the range it observed. For a Point that
/// is exactly right - a new customer somewhere in the covered area. For a <b>Polygon or a
/// LineString it is not</b>: each vertex is drawn from the whole continent, so a "service area"
/// comes out as a scribble spanning the map, and a few hundred of them render as a solid block of
/// colour. The shapes are valid; they are just not anywhere.
/// </para>
/// <para>
/// Fixing this in the generator would mean teaching it that some arrays are spatially correlated,
/// which is a lot of semantics to push into a tool whose job is "documents like these". So the demo
/// seeder does it instead: keep the ring's <i>relative</i> shape, and map it into a small box around
/// a point the document already carries. The result is still generated - just somewhere.
/// </para>
/// </remarks>
static string Localise(string json, uint seed)
{
    JsonNode? root;
    try
    {
        root = JsonNode.Parse(json);
    }
    catch (JsonException)
    {
        return json;
    }

    if (root is not JsonObject obj)
        return json;

    // The anchor is the document's own Point, so a service area surrounds its customer and a route
    // starts near its delivery address.
    var anchor = FindPoint(obj);
    if (anchor is null)
        return json;

    // A quarter of a degree is roughly a city and its surroundings - big enough to see, small
    // enough that several hundred of them do not merge into one blob.
    var spanLng = 0.08 + (seed & 0xFF) / 255.0 * 0.22;
    var spanLat = 0.06 + ((seed >> 8) & 0xFF) / 255.0 * 0.16;

    // A Point is already right - the generator placing one anywhere in the covered area is exactly
    // what it should do. Only multi-vertex shapes need pulling back together.
    var shapes = FindGeometries(obj)
        .Select(g => (Geometry: g, Type: g["type"]?.GetValue<string>(), Coordinates: g["coordinates"]))
        .Where(g => g.Type is not (null or "Point") && g.Coordinates is not null)
        .Select(g => (g.Type, g.Coordinates, Vertices: Vertices(g.Coordinates).ToList()))
        .Where(g => g.Vertices.Count >= 2);

    var changed = false;
    foreach (var (type, coordinates, vertices) in shapes)
    {
        double minX = vertices.Min(v => v.X), maxX = vertices.Max(v => v.X);
        double minY = vertices.Min(v => v.Y), maxY = vertices.Max(v => v.Y);
        var width = maxX - minX;
        var height = maxY - minY;

        foreach (var (node, x, y) in vertices)
        {
            // Normalised into 0..1 across the shape's own bounding box, then dropped into a small
            // box around the anchor - so the shape keeps its outline and loses its scale.
            var nx = width <= 0 ? 0.5 : (x - minX) / width;
            var ny = height <= 0 ? 0.5 : (y - minY) / height;

            node[0] = Math.Round(anchor.Value.Lng + (nx - 0.5) * spanLng, 5);
            node[1] = Math.Round(anchor.Value.Lat + (ny - 0.5) * spanLat, 5);
        }

        // A polygon's ring is an ordered boundary, and the generator emits its vertices in the order
        // it happened to make them - so the outline crosses itself and draws as a sliver or an
        // arrowhead rather than an area. Sorting each ring by angle about its own centroid turns any
        // set of points into a simple, non-self-intersecting shape.
        //
        // Only for rings: a LineString is a route, and its order is the whole point of it.
        if (type is "Polygon" or "MultiPolygon")
        {
            foreach (var ring in Rings(coordinates))
                Wind(ring);
        }

        changed = true;
    }

    return changed ? root.ToJsonString() : json;
}

/// <summary>The first Point in a body, used as the anchor its other geometry is arranged around.</summary>
static (double Lng, double Lat)? FindPoint(JsonObject obj)
{
    var points = FindGeometries(obj).Where(g => g["type"]?.GetValue<string>() == "Point");

    foreach (var geometry in points)
    {
        if (geometry["coordinates"] is JsonArray { Count: >= 2 } pair
            && pair[0] is JsonValue lng && pair[1] is JsonValue lat)
        {
            return (lng.GetValue<double>(), lat.GetValue<double>());
        }
    }

    return null;
}

static IEnumerable<JsonObject> FindGeometries(JsonNode? node)
{
    switch (node)
    {
        case JsonObject obj:
            if (obj["type"]?.GetValueKind() == JsonValueKind.String && obj.ContainsKey("coordinates"))
            {
                yield return obj;
                yield break;
            }

            foreach (var (_, value) in obj)
                foreach (var found in FindGeometries(value))
                    yield return found;
            break;

        case JsonArray array:
            foreach (var value in array)
                foreach (var found in FindGeometries(value))
                    yield return found;
            break;
    }
}

/// <summary>
/// The closed rings inside a Polygon / MultiPolygon coordinates value - the arrays whose own
/// elements are coordinate pairs.
/// </summary>
static IEnumerable<JsonArray> Rings(JsonNode? node)
{
    if (node is not JsonArray array || array.Count == 0)
        yield break;

    if (array[0] is JsonArray first && first.Count >= 2 && first[0]?.GetValueKind() == JsonValueKind.Number)
    {
        yield return array;
        yield break;
    }

    foreach (var child in array)
        foreach (var found in Rings(child))
            yield return found;
}

/// <summary>
/// Reorders a ring's vertices anticlockwise about their centroid and re-closes it, so the outline
/// is a simple polygon rather than a self-crossing scribble.
/// </summary>
static void Wind(JsonArray ring)
{
    var points = ring.OfType<JsonArray>()
        .Where(p => p.Count >= 2)
        .Select(p => (Node: p, X: p[0]!.GetValue<double>(), Y: p[1]!.GetValue<double>()))
        .ToList();

    // GeoJSON repeats the first vertex last to close the ring; sorting it as an ordinary point
    // would leave a duplicate somewhere in the middle.
    if (points.Count > 1
        && Math.Abs(points[0].X - points[^1].X) < 1e-9
        && Math.Abs(points[0].Y - points[^1].Y) < 1e-9)
    {
        points.RemoveAt(points.Count - 1);
    }

    if (points.Count < 3)
        return;

    var cx = points.Average(p => p.X);
    var cy = points.Average(p => p.Y);
    var ordered = points.OrderBy(p => Math.Atan2(p.Y - cy, p.X - cx)).ToList();

    ring.Clear();
    foreach (var point in ordered)
        ring.Add(new JsonArray(JsonValue.Create(point.X), JsonValue.Create(point.Y)));

    // Close it again.
    ring.Add(new JsonArray(JsonValue.Create(ordered[0].X), JsonValue.Create(ordered[0].Y)));
}

/// <summary>Every [lng, lat] pair inside a coordinates value, at whatever nesting depth it sits.</summary>
static IEnumerable<(JsonArray Node, double X, double Y)> Vertices(JsonNode? node)
{
    if (node is not JsonArray array)
        yield break;

    if (array.Count >= 2 && array[0] is JsonValue x && array[1] is JsonValue y
        && x.GetValueKind() == JsonValueKind.Number && y.GetValueKind() == JsonValueKind.Number)
    {
        yield return (array, x.GetValue<double>(), y.GetValue<double>());
        yield break;
    }

    foreach (var child in array)
        foreach (var found in Vertices(child))
            yield return found;
}

static string Quote(string? value)
    => value is null ? "NULL" : "'" + value.Replace("'", "''", StringComparison.Ordinal) + "'";

/// <summary>
/// Microsoft.Data.Sqlite's DateTimeOffset text format - the one the library binds and
/// <c>Ado.Timestamp</c> parses back. Written differently and the tool reads a different value than
/// was stored, which is the trap seed-demo.py documents at the top of the file.
/// </summary>
static string Stamp(DateTimeOffset value)
    => value.ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss.ffffff+00:00", CultureInfo.InvariantCulture);

/// <summary>
/// FNV-1a. Not <see cref="string.GetHashCode()"/>, which is randomised per process - the output file
/// has to be identical between runs, and that includes runs on different machines.
/// </summary>
static uint StableHash(string text)
{
    var hash = 2166136261u;
    foreach (var c in text)
    {
        hash ^= c;
        hash *= 16777619u;
    }

    return hash;
}

/// <summary>Walks up for the directory holding DocumentDb.slnx, so the tool runs from anywhere.</summary>
static string FindRepoRoot()
{
    var directory = new DirectoryInfo(AppContext.BaseDirectory);
    while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "DocumentDb.slnx")))
        directory = directory.Parent;

    return directory?.FullName
        ?? throw new InvalidOperationException("Could not locate the repository root (no DocumentDb.slnx above this assembly).");
}

/// <summary>What the database held before generating - see <c>Counts</c>.</summary>
sealed record Baseline(HashSet<string> Ids, DateTimeOffset Earliest, DateTimeOffset Latest);
