<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <IsPackable>false</IsPackable>
        <EnableAotAnalyzer>false</EnableAotAnalyzer>
        <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\ShinyDocDbMyAdmin\ShinyDocDbMyAdmin.csproj"/>
    </ItemGroup>
</Project>
