<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
        <PackageReference Include="JsonSchema.Net"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Shiny.DocumentDb.JsonSchema\Shiny.DocumentDb.JsonSchema.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.DocumentDb.Sqlite\Shiny.DocumentDb.Sqlite.csproj"/>
    </ItemGroup>
</Project>
