using Sample.ODataApi;
using Shiny.DocumentDb;
using Shiny.DocumentDb.AspNetCore.OData;
using Shiny.DocumentDb.Sqlite;

// ═══════════════════════════════════════════════════════════════════════════
// Shiny.DocumentDb — Sample OData v4 API (SQLite-backed)
//
//   • A SQLite document store holds Customers and Orders.
//   • A registered seeder fills the store once at startup (run-once marker) with ~250 customers and
//     ~1,000 orders generated by Bogus (fixed seed → deterministic), plus stable anchor records.
//   • Two OData entity sets are exposed: /odata/customers and /odata/orders.
//
// Browse http://localhost:5099/ for a list of example query URLs to try.
// ═══════════════════════════════════════════════════════════════════════════

var builder = WebApplication.CreateBuilder(args);

var dbPath = Path.Combine(Path.GetTempPath(), "sample-odata-api.db");

builder.Services
    // 1. SQLite-backed document store (default, unnamed). A source-generated JsonSerializerContext means
    //    the store runs with NO reflection (UseReflectionFallback = false) — the fast, AOT/trim-safe path.
    .AddDocumentStore(opts =>
    {
        opts.DatabaseProvider = new SqliteDatabaseProvider($"Data Source={dbPath}");
        opts.JsonSerializerOptions = SampleJsonContext.Default.Options;
        opts.UseReflectionFallback = false;
        opts.MapTypeToTable<Customer>("customers");
        opts.MapTypeToTable<Order>("orders");
    })
    // 2. Seed sample data once at startup. Bump the version to force a re-seed after editing SeedData.
    .AddDocumentSeeder("sample-data", version: 2, seed: SeedData.SeedAsync)
    // 3. Expose the two document types as OData entity sets (key defaults to "Id").
    .AddDocumentODataEndpoints(edm =>
    {
        // API-wide governance defaults — every entity set inherits these unless it overrides them.
        edm.ConfigureDefaultPolicy(p =>
        {
            p.DefaultPageSize = 25;        // applied when the client omits $top
            p.MaxTop = 100;                // a larger $top is rejected with 400
            p.MaxSkip = 10_000;
            p.MaxFilterNodeCount = 50;     // reject pathologically complex $filter trees
            p.MaxOrderByNodeCount = 3;
        });

        // Per-entity-set allowlists: only these properties may be filtered / sorted / selected.
        edm.EntitySet<Customer>("customers", p =>
        {
            p.FilterableProperties.UnionWith(["Name", "Country", "Age", "IsActive", "Created", "Email"]);
            p.SortableProperties.UnionWith(["Name", "Age", "Created"]);
            p.SelectableProperties.UnionWith(["Id", "Name", "Country", "Age", "IsActive", "Created", "Email"]);
        });
        edm.EntitySet<Order>("orders", p =>
        {
            p.FilterableProperties.UnionWith(["Status", "Total", "Country", "CustomerName", "Placed"]);
            p.SortableProperties.UnionWith(["Total", "Placed", "Id"]);
            p.SelectableProperties.UnionWith(["Id", "CustomerId", "CustomerName", "Status", "Total", "Country", "Placed"]);
        });
    });

var app = builder.Build();

// Serve the interactive query explorer (wwwroot/index.html) at the application root.
app.UseDefaultFiles();
app.UseStaticFiles();

app.MapDocumentODataEntitySet<Customer>("odata/customers");
app.MapDocumentODataEntitySet<Order>("odata/orders");

app.Run();
